import type { Metadata } from "next";
import { La_Belle_Aurore } from "next/font/google";
import "./globals.css";

const labella = La_Belle_Aurore({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={labella.className}>{children}</body>
    </html>
  );
}
